using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Hada
{
    internal class Coordenada
    {
        private int fila;
        private int columna;

        public int Fila { get; set; }
        public int Columna { get; set; }

        public Coordenada()
        {
            this.fila = 0;
            this.columna = 0;
        }
        public Coordenada(int fila, int columna)
        {
            this.fila = fila;
            this.columna = columna;
        }
        public Coordenada(string fila, string columna)
        {
            this.fila = int.Parse(fila);
            this.columna = int.Parse(columna);
        }

        public Coordenada(Coordenada c)
        {
            this.fila = c.Fila;
            this.columna = c.Columna;
        }

        public override string ToString()
        {
            return "(" + this.fila + "," + this.columna + ")";
        }

        public override int GetHashCode()
        {
            return this.Fila.GetHashCode() ^ this.Columna.GetHashCode();
        }

        public override bool Equals(object obj)
        {
            if (obj is Coordenada c)
            {
                return (this.Fila == c.Fila && this.Columna == c.Columna);
            } else
            {
                return false;
            }
        }

        public bool Equals(Coordenada c)
        {
            return (this.Fila == c.Fila && this.Columna == c.Columna);
        }

        /*
        public override bool Equals(object obj)
        {
            return obj is Coordenada coordenada &&
                   fila == coordenada.fila &&
                   columna == coordenada.columna &&
                   Fila == coordenada.Fila &&
                   Columna == coordenada.Columna;
        }

        public override int GetHashCode()
        {
            int hashCode = 316220930;
            hashCode = hashCode * -1521134295 + fila.GetHashCode();
            hashCode = hashCode * -1521134295 + columna.GetHashCode();
            hashCode = hashCode * -1521134295 + Fila.GetHashCode();
            hashCode = hashCode * -1521134295 + Columna.GetHashCode();
            return hashCode;
        }
        */ // Generated by vs


    }
}
